name: deploy flutter web (github pages)

on:
  push:
    branches: [ "master", "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/drum_tuner_app
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - name: deps
        run: flutter pub get
      - name: build
        run: flutter build web --release --base-href "/drum_tuner/"
      - name: spa fallback
        run: cp build/web/index.html build/web/404.html
      - name: upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: apps/drum_tuner_app/build/web

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
